@startuml sequence_diagram
actor 您
您 -> 爬虫主体 : 1.1 运行
爬虫主体 -> 对应站点 : 1.2 发起 http 请求
对应站点 -> 爬虫主体 : 1.3 响应数据
爬虫主体 -> 爬虫主体 : 1.4 处理数据
爬虫主体 -> 数据库 : 1.5 通过 ORM 存入
爬虫主体 [#0000FF]-> 您 : 1.6 通知
您 -> API : 2.1 运行
API -> API : 2.2 在 http://localhost:5000 开启 web 服务
API -> 数据库 : 2.3 获取对应规则数据
数据库 -> API : 2.4 返回对应规则数据
API [#0000FF]-> 您 : 2.5 返回主页
@enduml